name: Cypress Component Tests

on:
  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  test:
    name: Running Cypress Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - name: Install dependencies
        run: npm install

      - name: Run Cypress component tests
        run: npm run test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-results
          path: |
            cypress/videos/
            cypress/screenshots/
          retention-days: 5
